# Couleurs auto-générées par Matugen (Base)
background            #151218
foreground            #e8e0e8
cursor                #d9bafa

# Palette ANSI 0-7 (Les indispensables)
color0  #100d12
color1  #ffb4ab
color2  #d9bafa
color3  #f2b7bf
color4  #d0c1da
color5  #93000a
color6  #543b71
color7  #e8e0e8

# Palette ANSI 8-15 (Versions brillantes)
color8  #3c383e
color9  #ffb4ab
color10 #d9bafa
color11 #f2b7bf
color12 #d0c1da
color13 #93000a
color14 #543b71
color15 #ccc4cf
