# IMPORT DES COULEURS MATUGEN
source = ~/.config/hypr/hyprlock-colors.conf

general {
    no_fade_in = true
    grace = 0
    disable_loading = true
}

background {
    monitor =
    #color = $background
    path = ~/current_wallpaper/background.jpg 
    blur_passes = 0
}

# HEURE RETRO
label {
    monitor =
    text = $TIME
    color = $primary
    font_size = 64
    font_family = $font_family
    position = 0, 80
    halign = center
    valign = center
}

# INPUT FIELD (Style i3 rectangulaire)
input-field {
    monitor =
    size = 280, 45
    outline_thickness = 2
    
    # On utilise les variables sourcées
    outer_color = $entry_border_color
    inner_color = $entry_background_color
    font_color = $entry_color
    
    # On force les angles droits (Retro-look)
    rounding = 0
    
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    fade_on_empty = false
    placeholder_text = "Password..."
    hide_input = false
    
    position = 0, -20
    halign = center
    valign = center
}

# USER INFO
label {
    monitor =
    text = $USER
    color = $text_color
    font_size = 14
    font_family = $font_family
    position = 0, -85
    halign = center
    valign = center
}
