local M = {}

M.base_30 = {
  white = "<{{colors.on_surface.hex}}>",
  darker_black = "#11111b", -- Valeur fixe pour garantir le contraste
  black = "#181825",        -- Valeur fixe pour le fond
  black2 = "#1e1e2e",       -- Valeur fixe
  one_bg = "#313244",
  one_bg2 = "#45475a",
  one_bg3 = "#585b70",
  grey = "<{{colors.on_surface_variant.hex}}>",
  grey_status = "<{{colors.outline.hex}}>",
  line = "#313244",
  red = "<{{colors.red.hex}}>",
  pink = "<{{colors.magenta.hex}}>",
  dark_purple = "<{{colors.magenta.hex}}>",
  purple = "<{{colors.magenta.hex}}>",
  blue = "<{{colors.blue.hex}}>",
  cyan = "<{{colors.cyan.hex}}>",
  green = "<{{colors.green.hex}}>", 
  yellow = "<{{colors.yellow.hex}}>",
}

return M
